# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ag1g5BCsw6YTpzEWG2ZhETjyathyjE4U
"""

# Importing the required packages
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelBinarizer
import seaborn as sns
from sklearn.svm import SVC

# Loding the dataset
data = pd.read_csv("/content/Fish.csv")

# shape of the dataframe
data.shape

# lets print the count of target
data['Species'].value_counts()

# taking all the independent values in x and class value in y
x = data.drop(columns = ['Species'],axis = 1)
y = data['Species']

# printing x
x.head()

# printing y
y.head()

# calling the model
model= SVC()

# fitting the support vector machine  
model.fit(x, y)

import pickle

# Save the model
pickle.dump(model, open('model.pkl','wb'))

# Loading model to compare the results
model = pickle.load(open('model.pkl','rb'))
print(model.predict([[340.0,	23.9,	26.5,	31.1,	12.3778,	4.6961]]))